#!/bin/bash
INPUT_PATH="./data/public-test-data/"
OUTPUTPATH="/tmp/output"

rm -rf "$OUTPUTPATH"
mkdir -p "$OUTPUTPATH"
podman system prune -f
podman build . -t 555
podman run -v "$INPUT_PATH":/mnt/input -v "$OUTPUTPATH":/mnt/output 555
